//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.10 at 10:29:08 AM EDT 
//


package util.geode.monitor.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mxBeanType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="mxBeanType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DistributedSystemMXBean"/>
 *     &lt;enumeration value="MemberMXBean"/>
 *     &lt;enumeration value="CacheServerMXBean"/>
 *     &lt;enumeration value="DiskStoreMXBean"/>
 *     &lt;enumeration value="RegionMXBean"/>
 *     &lt;enumeration value="DistributedRegionMXBean"/>
 *     &lt;enumeration value="LockServiceMXBean"/>
 *     &lt;enumeration value="DistributedLockServiceMXBean"/>
 *     &lt;enumeration value="GatewaySenderMXBean"/>
 *     &lt;enumeration value="GatewayReceiverMXBean"/>
 *     &lt;enumeration value="AsyncEventQueueMXBean"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "mxBeanType")
@XmlEnum
public enum MxBeanType {

    @XmlEnumValue("DistributedSystemMXBean")
    DISTRIBUTED_SYSTEM_MX_BEAN("DistributedSystemMXBean"),
    @XmlEnumValue("MemberMXBean")
    MEMBER_MX_BEAN("MemberMXBean"),
    @XmlEnumValue("CacheServerMXBean")
    CACHE_SERVER_MX_BEAN("CacheServerMXBean"),
    @XmlEnumValue("DiskStoreMXBean")
    DISK_STORE_MX_BEAN("DiskStoreMXBean"),
    @XmlEnumValue("RegionMXBean")
    REGION_MX_BEAN("RegionMXBean"),
    @XmlEnumValue("DistributedRegionMXBean")
    DISTRIBUTED_REGION_MX_BEAN("DistributedRegionMXBean"),
    @XmlEnumValue("LockServiceMXBean")
    LOCK_SERVICE_MX_BEAN("LockServiceMXBean"),
    @XmlEnumValue("DistributedLockServiceMXBean")
    DISTRIBUTED_LOCK_SERVICE_MX_BEAN("DistributedLockServiceMXBean"),
    @XmlEnumValue("GatewaySenderMXBean")
    GATEWAY_SENDER_MX_BEAN("GatewaySenderMXBean"),
    @XmlEnumValue("GatewayReceiverMXBean")
    GATEWAY_RECEIVER_MX_BEAN("GatewayReceiverMXBean"),
    @XmlEnumValue("AsyncEventQueueMXBean")
    ASYNC_EVENT_QUEUE_MX_BEAN("AsyncEventQueueMXBean");
    private final String value;

    MxBeanType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MxBeanType fromValue(String v) {
        for (MxBeanType c: MxBeanType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
